#for single job
# parallel jobs running
# name : Hello #name of workflow
# on : workflow_dispatch #this says that workflow runs on manual trigger
# jobs : #jobs that workflow should do when triggered
#   hello: #name of our job 1
#     runs-on: ubuntu-latest # runner where the job should run 
#     steps: #steps the jobs should follow
#       - name: hello_step #first step name
#         # run: echo " Welcome to github action" # to run single command
#         # to run multiple commands
#         run: |
#           echo "Line one"
#           echo "Line two"

# to create multiple jobs in single workflow
# name : Hello #name of workflow
# on : workflow_dispatch #this says that workflow runs on manual trigger
# jobs : #jobs that workflow should do when triggered
#   build: # mandatorily needs the runs-on field
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build step
#         run : echo "A demo build"
#   #2nd job is to test
#   test:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Test Phase
#           run : echo "Running test cases"
#   #3rd job is 
#   deploy :
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy the app
#         run: echo "deploying the app"



  # now to make jobs run sequentially, i.e only after build, test job should run and then test
  #  use needs as below
  
# name : Hello #name of workflow
# on : workflow_dispatch #this says that workflow runs on manual trigger
# jobs : #jobs that workflow should do when triggered
#   build: # mandatorily needs the runs-on field
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build step
#         run : echo "A demo build"
#   #2nd job is to test
#   test:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#         - name: Test Phase
#           run : echo "Running test cases"
#   #3rd job is 
#   deploy :
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - name: Deploy the app
#         run: echo "deploying the app"



# TRIGGERS :
# Types of triggers :
# 1. Event based trigger : when a specific event happens in the repository, workflow will be triggered. Ex: push, pull request, release, etc
# 2. Schedule based trigger : workflow will be triggered at a specific time or interval. Ex: every day at 12 PM, every Monday, etc
# 3. Manual trigger : workflow will be triggered manually by a user. Ex: using workflow_dispatch event
# 4. Workflow trigger : one workflow can trigger another workflow using workflow_run event 

# to trigger workflow on push event
# name : Hello
# on : push
# jobs :
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build step
#         run: echo " build step running"

# # to trigger workflow on both pull and push events
# name : Hello
# on : ["push", "pull_request"]
# jobs :
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build step
#         run: echo " build step running"

# # to trigger workflow based on branches and pull request from dev to target branch main
# name : Hello
# on : 
#   push:
#     branches : 
#       - main
#       - dev 
#   pull_request:
#     branches :
#       - main
# jobs :
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build step
#         run: echo " build step running" 


# # to trigger workflow only when pull request is opened
# name : Hello
# on : 
#   push:
#     branches : 
#       - main
#       - dev 
#   pull_request:
#     type:
#       - opened
#     branches :
#       - main
# jobs :
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: build step
#         run: echo " build step running" 


#  ---------------------------------------

# variables in github actions :
# variables are used to store values that can be used in workflows and jobs. There are two types of variables in github actions :
# 1. Environment variables : these are predefined variables that are available in all workflows and jobs. Ex: GITHUB_REPOSITORY, GITHUB_REF, GITHUB_SHA, etc
# 2. Custom variables : these are user defined variables that can be used in workflows and jobs. Ex: MY_VARIABLE, etc

# variables holds peice of information and are used to store non sensitive data. For sensitive data we use secrets in github actions.

#after creating a custom var we use it in our job workflow like this
# name : Hello 
# on : push 
# jobs : 
#   build: 
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build step
#         run : echo "Hello, ${{ vars.MY_NAME }}"




#secrets : used to store sensitive data like API keys, passwords, etc. 
#Secrets are encrypted and can only be accessed by workflows and jobs that have permission to access them. 
#Secrets are stored in the repository settings and can be accessed using the secrets context in github actions.

# name: Hello
# on: push
# jobs:
#    build:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Build Step
#          run: echo " ${{ secrets.DOCKER_PASSWORD }}"



#------------------------------------------------

#Git hub actions: Action in git hub is a reusable application or set of code performs the specific task within the workflow
# Checkout action

name: Git hub action
on: push 
jobs:
   action-demo :
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the action
         uses: actions/checkout@v4  #uses keyword is used for using action in the workflow
       - name: Print index.html file
         run: cat index.html


