name: Context variables name
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "Workflow triggered by ${{ github.actor }}"
          echo "Repo name : ${{ github.repository }}"
          echo "The branch is ${{ github.ref_name }}"

      - name: Print all vars under github context object
        run: echo "${{ toJson(github) }}"

      - name: Print environment variables
        run: printenv
